use_frameworks!

platform :ios, '8.0'

target 'TXPermissionManager_Example' do
  pod 'TXPermissionManager', :path => '../'

  target 'TXPermissionManager_Tests' do
    inherit! :search_paths

    
  end
end
